# Generated by Django 4.2.6 on 2024-03-18 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduleentry',
            name='period',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM.lessontime', unique=True),
        ),
    ]
