# Generated by Django 4.2.6 on 2024-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0003_classroomsubject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroomsubject',
            name='subject',
        ),
        migrations.AddField(
            model_name='classroomsubject',
            name='subject',
            field=models.ManyToManyField(blank=True, null=True, to='SM.subject'),
        ),
    ]
