# Generated by Django 4.2.6 on 2024-03-23 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0004_remove_classroomsubject_subject_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroomsubject',
            name='subject',
            field=models.ManyToManyField(blank=True, to='SM.subject'),
        ),
    ]
