# Generated by Django 4.2.6 on 2024-03-23 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SM', '0005_alter_classroomsubject_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayofweek', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable', to='SM.classroom')),
                ('period', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SM.lessontime')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SM.subject')),
            ],
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='daily_schedule',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='period',
        ),
        migrations.RemoveField(
            model_name='scheduleentry',
            name='subject',
        ),
        migrations.AlterField(
            model_name='classroomsubject',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='SM.classroom'),
        ),
        migrations.DeleteModel(
            name='DailySchedule',
        ),
        migrations.DeleteModel(
            name='ScheduleEntry',
        ),
    ]
