# Generated by Django 4.2.6 on 2024-03-13 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_User', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacher',
            options={'verbose_name': 'Teacher_User', 'verbose_name_plural': 'Teacher_Users'},
        ),
    ]
