# Generated by Django 4.2.6 on 2024-03-14 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_User', '0002_alter_teacher_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
