# Generated by Django 4.2.6 on 2024-03-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lessons',
            name='time',
        ),
        migrations.AlterField(
            model_name='lessons',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
