# Generated by Django 4.2.6 on 2024-03-16 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lessons',
            name='grade',
            field=models.CharField(choices=[('T', 'Tốt'), ('K', 'Khá'), ('TB', 'Trung Bình'), ('Y', 'Yếu')], default='TB', max_length=2),
        ),
        migrations.AlterField(
            model_name='student',
            name='classroom',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='CM.classroom'),
        ),
    ]
