# Generated by Django 4.2.6 on 2024-03-14 17:13

import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0002_remove_lessons_time_alter_lessons_date_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Mark', models.JSONField(default=list, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CM.student')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CM.subject')),
            ],
        ),
    ]
