# Generated by Django 4.2.6 on 2024-03-18 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CM', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seat',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seat', to='CM.student'),
        ),
    ]
